/* generated by tools/level_presets.py: the level trim of each factory preset, 1/2 dB */
#pragma once
#define PT_ENGINES 6u
#define PT_MAX 32u
static const int8_t PRESET_TRIM[PT_ENGINES][PT_MAX] = {
    {/* 0.0 808 BOOM */ -9, /* 0.1 808 DIRTY */ -3, /* 0.2 SUB BASS */ -10, /* 0.3 808 SLIDE */ -4, /* 0.4 ACID 303 */ 23, /* 0.5 PLUGG BASS */ -6, /* 0.6 REESE */ 3, /* 0.7 WOBBLE */ 7, /* 0.8 FUNK BASS */ 16, /* 0.9 G-FUNK LD */ -10, /* 0.10 TRAP PLUCK */ 23, /* 0.11 SYN BRASS */ 23, /* 0.12 SUPERSAW */ -18, /* 0.13 WARM PAD */ -7, /* 0.14 DARK STR */ -4, /* 0.15 ATMOS PAD */ -9, /* 0.16 PAN FLUTE */ -7, /* 0.17 FAT LEAD */ -5, /* 0.18 MONO BASS */ 14, /* 0.19 PWM LEAD */ -6, /* 0.20 SAW BASS */ 17, /* 0.21 SINE PAD */ -23},
    {/* 1.0 FAT BASS */ 23, /* 1.1 MIN STAB */ 23, /* 1.2 MIN7 STAB */ 23, /* 1.3 RAVE STAB */ 23, /* 1.4 DUB CHORD */ 23, /* 1.5 SAW PAD */ -11, /* 1.6 SYNC LEAD */ -3, /* 1.7 HOOVER */ 5, /* 1.8 ACCORDION */ 12, /* 1.9 ENSEMBLE */ -7, /* 1.10 80S POLY */ 17, /* 1.11 SQR LEAD */ -8, /* 1.12 POWER STAB */ 23, /* 1.13 PULSE PAD */ -15},
    {/* 2.0 TINE EP */ -1, /* 2.1 GLASS BELL */ 4, /* 2.2 ROUND BASS */ 14, /* 2.3 BRASS SECT */ 23, /* 2.4 SOFT PAD */ 2, /* 2.5 WOOD BARS */ 23, /* 2.6 DRAWBARS */ 11, /* 2.7 NYLON PICK */ 23},
    {/* 3.0 GRAND PNO */ 17, /* 3.1 GM KIT */ 0, /* 3.2 DUSTY PNO */ 19, /* 3.3 LOFI KEYS */ 11},
    {/* 4.0 ACID CLASS */ 0, /* 4.1 ACID SQUARE */ 0, /* 4.2 SQUELCH */ 0, /* 4.3 ACID RAT */ 0, /* 4.4 SOFT 303 */ 0, /* 4.5 DEEP 303 */ 0, /* 4.6 SCREAMER */ 0, /* 4.7 RUBBER 303 */ 0},
    {/* 5.0 VOX PAD */ 0, /* 5.1 CHOIR WAVE */ 0, /* 5.2 GLASS KEYS */ 0, /* 5.3 DIGI LEAD */ 0, /* 5.4 SYNC LEAD W */ 0, /* 5.5 FM BELL */ 0, /* 5.6 HOLLOW PAD */ 0, /* 5.7 REED LEAD */ 0, /* 5.8 CLAVI PLUCK */ 0, /* 5.9 METAL PLUCK */ 0, /* 5.10 WAVE BASS */ 0, /* 5.11 ORGAN WAVE */ 0},
};
