#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""The tables X0X's 909 (firmware/src/x0x/drum909*.{c,h}) needs, for NoteSorcery's 909 CM kit.

A port of X0X's tools/gen_drum_samples.py (Charles Vestal, GPL-3.0), its tables part, unchanged:

  x0x_drum_tables.h   the tanh lookup every saturator uses, and 9W9's EXP pot curves (er99_pots.h:
                      min * (max/min)^(pot/127)) evaluated here in float as 9W9 computes them with libm

and, instead of the hi-hat, ride and crash recordings (220 KB of flash), a header with a silent sample each:
NoteSorcery's 909 CM kit plays its hats and cymbals with SLOOP's synthesised 909 sounds (firmware/src/drums.c).

  tools/gen_x0x_tables.py build/gen/x0x_drum_tables.h      (x0x_drum_samples.h is written next to it)
"""
import math
import struct
import sys
from pathlib import Path

EXP_RANGES = [
    ("BD_DECAY", 100.0, 4000.0), ("BD_PITCH", 0.43, 4.7), ("DRIVE", 0.85, 12.0),
    ("SD_TUNE", 130.0, 320.0), ("SD_TONE", 300.0, 4000.0),
    ("LT_TUNE", 50.0, 90.0), ("LT_DECAY", 80.0, 2600.0),
    ("MT_TUNE", 80.0, 125.0), ("MT_DECAY", 70.0, 2200.0),
    ("HT_TUNE", 110.0, 170.0), ("HT_DECAY", 60.0, 2000.0),
    ("RS_TUNE", 150.0, 300.0), ("CP_TUNE", 650.0, 1400.0), ("CP_TAIL", 120.0, 1000.0),
    ("OH_DECAY", 20.0, 1200.0), ("CH_DECAY", 15.0, 300.0), ("CY_DECAY", 100.0, 3000.0),
    ("SMP_PITCH", 0.25, 4.0), ("FX_HPF", 30.0, 800.0),
]
TANH_N = 1024
TANH_MAX = 8.0


def f32(x):
    return struct.unpack("<f", struct.pack("<f", x))[0]


def cfloat(x):
    s = repr(f32(x))
    if "e" not in s and "." not in s:
        s += ".0"
    return s + "f"


def pot_exp(lo, hi, pot):
    ratio = f32(f32(hi) / f32(lo))
    t = f32(pot / 127.0)
    return f32(f32(lo) * f32(ratio ** t))


def main(out_t):
    out_t = Path(out_t)
    out_s = out_t.parent / "x0x_drum_samples.h"
    out_t.parent.mkdir(parents=True, exist_ok=True)
    s = ["/* Generated by tools/gen_x0x_tables.py -- do not edit. NoteSorcery: no 909 recordings in the firmware",
         " * (its 909 CM kit plays SLOOP's synthesised hats and cymbals): one silent sample each. */",
         "#pragma once", "#include <stdint.h>"]
    for name in ("x0x_smp_hh", "x0x_smp_ride", "x0x_smp_crash"):
        s.append(f"#define {name.upper()}_LEN 1u")
        s.append(f"static const int16_t {name}[1] = {{0}};")
    out_s.write_text("\n".join(s) + "\n")
    tab = [f32(math.tanh(TANH_MAX * i / TANH_N)) for i in range(TANH_N + 2)]
    t = ["/* Generated by tools/gen_x0x_tables.py (after X0X's tools/gen_drum_samples.py) -- do not edit. */",
         "#pragma once", "",
         f"/* tanh(u) at u = i * {TANH_MAX} / {TANH_N}, i = 0..{TANH_N + 1} (one guard point) */",
         f"#define X0X_TANH_N {TANH_N}",
         f"#define X0X_TANH_SCALE {cfloat(TANH_N / TANH_MAX)}",
         "#ifdef X0X_DRUM_TABLES_DEFINE",
         f"const float x0x_tanh_tab[{len(tab)}] = {{"]
    for i in range(0, len(tab), 6):
        t.append("    " + ", ".join(cfloat(v) for v in tab[i:i + 6]) + ",")
    t += ["};", "#else", f"extern const float x0x_tanh_tab[{len(tab)}];", "#endif", "",
          "/* 9W9 EXP pots (er99_pots.h): value = min * (max/min)^(pot/127), pot 0..127 */"]
    for i, (n, lo, hi) in enumerate(EXP_RANGES):
        t.append(f"#define X0X_EXP_{n} {i}   /* {lo:g} .. {hi:g} */")
    t.append(f"#define X0X_EXP_COUNT {len(EXP_RANGES)}")
    t.append("#ifdef X0X_DRUM_TABLES_DEFINE")
    t.append(f"const float x0x_pot_exp[{len(EXP_RANGES)}][128] = {{")
    for n, lo, hi in EXP_RANGES:
        vals = [pot_exp(lo, hi, p) for p in range(128)]
        t.append("    { /* " + n + " */")
        for i in range(0, 128, 6):
            t.append("        " + ", ".join(cfloat(v) for v in vals[i:i + 6]) + ",")
        t.append("    },")
    t += ["};", "#else", f"extern const float x0x_pot_exp[{len(EXP_RANGES)}][128];", "#endif", ""]
    out_t.write_text("\n".join(t))
    print(f"x0x tables: tanh {TANH_N + 2} + {len(EXP_RANGES)} pot curves -> {out_t.name}; silent 909 samples")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "x0x_drum_tables.h")
