#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""The WAVE engine's built-in single-cycle waves (NoteSorcery, firmware/src/eng_wave.c) into a C header.

Each wave is defined in the time domain (one cycle), measured to 128 harmonics (a DFT over 2048 points), then
rebuilt band-limited as a mip pyramid of WT_LEVELS tables: level l holds the harmonics up to 128 >> l in
max(32, 256 >> l) samples, so a note picks the level whose top harmonic stays under Nyquist (no aliasing). Every
wave is normalised on its loudest level (peak 30000; a level with fewer harmonics can peak higher than level 0,
and nothing may clip), and every level of it by the same factor, so a wave keeps its loudness up the keyboard. Stdlib only.

  gen_wavetables.py OUT.h
"""
import math
import sys

N = 2048                         # time-domain points of the definition
H = 128                          # harmonics measured
LEVELS = 8
LEN = [max(32, 256 >> l) for l in range(LEVELS)]
PEAK = 30000


def saw(x): return 1.0 - 2.0 * x
def square(x): return 1.0 if x < 0.5 else -1.0
def pulse(w): return lambda x: 1.0 if x < w else -1.0
def tri(x): return 4.0 * x - 1.0 if x < 0.5 else 3.0 - 4.0 * x
def sine(x): return math.sin(2 * math.pi * x)


def additive(amps, phase=0.0):
    """a sum of harmonics (1-based amplitudes)"""
    return lambda x: sum(a * math.sin(2 * math.pi * (k + 1) * x + phase * k) for k, a in enumerate(amps) if a)


def formant(centres, width):
    """harmonics shaped by resonances (a vowel), 64 of them"""
    amps = []
    for k in range(1, 65):
        f = k * 110.0
        a = sum(math.exp(-((f - c) / width) ** 2) for c in centres) + 0.15 / k
        amps.append(a / k ** 0.3)
    return additive(amps)


def fm(ratio, index):
    return lambda x: math.sin(2 * math.pi * x + index * math.sin(2 * math.pi * ratio * x))


def sync(ratio):
    return lambda x: 1.0 - 2.0 * ((x * ratio) % 1.0)


def stepped(bits):
    q = 2 ** (bits - 1)
    return lambda x: round(math.sin(2 * math.pi * x) * q) / q


def lowpassed(f, keep):
    """f with its harmonics above keep rolled off (done on the spectrum below: marked by a tuple)"""
    return ("lp", f, keep)


WAVES = [
    ("SINE", sine),
    ("TRI", tri),
    ("SAW", saw),
    ("SQUARE", square),
    ("PULSE25", pulse(0.25)),
    ("PULSE12", pulse(0.125)),
    ("ORGAN", additive([1, 1, 0.8, 0, 0.6, 0, 0, 0.5])),            # drawbars 8' 4' 2 2/3' 2' 1'
    ("ORGAN2", additive([1, 0.5, 1, 0.3, 0.6, 0.3, 0.4, 0, 0.3])),
    ("VOX A", formant([700, 1220, 2600], 260)),
    ("VOX O", formant([450, 800, 2830], 220)),
    ("BELL", additive([1, 0, 0.45, 0, 0.3, 0.6, 0, 0.25, 0, 0, 0.2, 0, 0.15])),
    ("BRASS", lowpassed(saw, 18)),
    ("REED", additive([1.0 / k ** 1.5 if k % 2 else 0.12 / k for k in range(1, 48)])),
    ("HOLLOW", additive([0, 0, 1, 0, 0.7, 0, 0.5, 0, 0.4])),
    ("FM 1", fm(1.0, 1.5)),
    ("FM 2", fm(3.0, 2.0)),
    ("SYNC", sync(2.5)),
    ("SYNC 2", sync(3.7)),
    ("DIGI", stepped(3)),
    ("GLASS", additive([1, 0, 0, 0, 0.5, 0, 0, 0, 0.35, 0, 0, 0, 0.2])),
    ("CLAVI", lowpassed(pulse(0.18), 40)),
    ("CHOIR", formant([600, 1040, 2250, 2450], 300)),
    ("METAL", additive([1, 0, 0.6, 0.0, 0.0, 0.7, 0.0, 0.5, 0, 0, 0, 0.45, 0, 0.3])),
    ("SOFTSAW", lowpassed(saw, 10)),
]


def spectrum(f):
    """the first H harmonics (cos, sin) of one cycle of f"""
    lp = None
    if isinstance(f, tuple):
        _, f, lp = f
    xs = [f(i / N) for i in range(N)]
    mean = sum(xs) / N
    xs = [v - mean for v in xs]
    re, im = [], []
    for k in range(1, H + 1):
        c = s = 0.0
        for i in range(N):
            a = 2 * math.pi * k * i / N
            c += xs[i] * math.cos(a)
            s += xs[i] * math.sin(a)
        g = 2.0 / N
        if lp:
            g /= math.sqrt(1.0 + (k / lp) ** 4)
        re.append(c * g)
        im.append(s * g)
    return re, im


def rebuild(re, im, hmax, length):
    out = []
    for i in range(length):
        v = 0.0
        for k in range(min(hmax, length // 2 - 1)):
            a = 2 * math.pi * (k + 1) * i / length
            v += re[k] * math.cos(a) + im[k] * math.sin(a)
        out.append(v)
    return out


def main(out):
    tables, names = [], []
    for name, f in WAVES:
        re, im = spectrum(f)
        lv = [rebuild(re, im, H >> l, LEN[l]) for l in range(LEVELS)]
        g = PEAK / max(1e-9, max(abs(v) for t in lv for v in t))   # (a level with fewer harmonics can peak higher)
        tables.append([[int(round(max(-32767, min(32767, v * g)))) for v in t] for t in lv])
        names.append(name)
    offs, o = [], 0
    for l in range(LEVELS):
        offs.append(o)
        o += LEN[l]
    lines = ["/* generated by tools/gen_wavetables.py: the WAVE engine's built-in single-cycle waves, each a",
             " * band-limited mip pyramid (level l: harmonics up to 128 >> l in WT_LEN[l] samples) */",
             "#pragma once",
             f"#define WT_BUILTIN {len(WAVES)}u",
             f"#define WT_LEVELS {LEVELS}u",
             f"#define WT_SIZE {o}u                 /* samples of one wave (every level) */",
             "static const uint16_t WT_OFF[WT_LEVELS] = {" + ", ".join(map(str, offs)) + "};",
             "static const uint16_t WT_LEN[WT_LEVELS] = {" + ", ".join(map(str, LEN)) + "};",
             "static const uint8_t WT_LEN_LOG2[WT_LEVELS] = {" + ", ".join(str(n.bit_length() - 1) for n in LEN) + "};",
             "#define WT_NAMES_INIT " + ", ".join(f'"{n}"' for n in names),
             "static const int16_t WT_DATA[WT_BUILTIN][WT_SIZE] = {"]
    for t, n in zip(tables, names):
        flat = [v for lvl in t for v in lvl]
        lines.append(f"    /* {n} */ {{")
        for i in range(0, len(flat), 16):
            lines.append("        " + ", ".join(map(str, flat[i:i + 16])) + ",")
        lines.append("    },")
    lines.append("};")
    with open(out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wavetables: {len(WAVES)} waves x {LEVELS} levels, {len(WAVES) * o * 2} B")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "ns_waves.h")
