#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""The Ableton Live Set templates (web/als/templates/*.xml, from NoteMove's core/src/main/resources/als) as one
script the browser editor loads next to web/als/nsals.js: web/als/als_templates.js. Run after editing a template.

  tools/gen_als_templates.py
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent / "web" / "als"
NAMES = {"head": "head.xml", "track": "miditrack.xml", "clip": "midiclip.xml", "scene": "scene.xml", "tail": "tail.xml"}


def main():
    t = {k: (HERE / "templates" / f).read_text(encoding="utf-8") for k, f in NAMES.items()}
    js = ["/* SPDX-License-Identifier: GPL-3.0-only */",
          "/* Generated by tools/gen_als_templates.py from web/als/templates/*.xml -- do not edit. The Live 11 set",
          " * skeleton NoteSorcery's .als export fills (web/als/nsals.js); from NoteMove's LiveSetExporter. */",
          "export const TEMPLATES = " + json.dumps(t, indent=1) + ";", ""]
    (HERE / "als_templates.js").write_text("\n".join(js), encoding="utf-8")
    print(f"als templates: {sum(len(v) for v in t.values())} characters -> web/als/als_templates.js")


if __name__ == "__main__":
    main()
